services:
  api:
    build: .
    container_name: hamnavaz-api
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: hamnavaz-postgres
    environment:
      POSTGRES_DB: hamnavaz
      POSTGRES_USER: hamnavaz
      POSTGRES_PASSWORD: hamnavaz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
