import Link from "next/link";
import { getMusician } from "../../../lib/api";

export default async function MusicianProfile({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  let data: Awaited<ReturnType<typeof getMusician>> | null = null;
  try { data = await getMusician(id); } catch {}
  if (!data) return <main className="container page-shell"><nav className="profile-nav"><Link className="profile-brand" href="/"><span>♪</span> همنواز</Link><Link href="/musicians" className="back-link">← نوازنده‌ها</Link></nav><div className="profile-empty">پروفایل پیدا نشد.</div></main>;
  const p = data.profile;
  const presenceLabel = p.is_online ? "● آنلاین" : "● آفلاین";
  return <main className="container profile-page">
    <nav className="profile-nav"><Link className="profile-brand" href="/"><span>♪</span> همنواز</Link><Link href="/musicians" className="back-link">← بازگشت به نوازنده‌ها</Link></nav>
    <section className="profile-hero-card">
      <div className="profile-avatar">{p.avatar_url ? <img src={p.avatar_url} alt={p.display_name || ""}/> : "♪"}<span className={p.is_online ? "profile-online online" : "profile-online offline"}>{presenceLabel}</span></div>
      <div className="profile-main-info"><p className="eyebrow">پروفایل نوازنده</p><h1>{p.display_name}</h1><p className="profile-location">📍 {p.city_name || p.city || "شهر ثبت نشده"}</p><div className="profile-tags"><span>عضو همنواز</span><span>پروفایل موسیقی</span>{p.is_verified && <span>✓ تأییدشده</span>}</div></div>
      <div className="profile-actions"><Link className="primary-btn" href={`/collaboration/${id}`}>درخواست همکاری <span>←</span></Link><Link className="secondary-btn" href={`/messages?user=${id}`}>ارسال پیام</Link></div>
    </section>
    <section className="profile-content-grid"><article className="profile-panel profile-about"><div className="panel-kicker">01</div><h2>درباره من</h2><p>{p.bio || "این نوازنده هنوز توضیحی درباره خودش ثبت نکرده است."}</p></article><article className="profile-panel"><div className="panel-kicker">02</div><h2>ساز و مهارت</h2>{data.instruments.length ? <div className="profile-skills">{data.instruments.map((x, i) => <div className="profile-skill" key={String(x.id ?? i)}><span className="skill-icon">♫</span><div><strong>{String(x.instrument_id ?? "ساز")}</strong><small>{String(x.level ?? "فعال")}</small></div></div>)}</div> : <p className="muted">هنوز سازی ثبت نشده است.</p>}</article></section>
    <section className="profile-next"><div><p className="eyebrow">قدم بعدی</p><h2>برای یک همکاری واقعی آماده‌ای؟</h2><p>یک پیام بفرست و گفت‌وگو را برای تمرین، هم‌نوازی یا اجرا شروع کن.</p></div><Link className="primary-btn" href={`/collaboration/${id}`}>شروع همکاری ←</Link></section>
    <style>{`
      .profile-page{padding-bottom:80px}.profile-nav{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.06)}.profile-brand{font-family:Estedad,Vazirmatn,sans-serif;font-size:20px;font-weight:900}.profile-brand span{color:#d9b45b;margin-left:7px}.back-link{color:#9ba6b8;font-size:13px;font-weight:700}.back-link:hover{color:#d9b45b}
      .profile-hero-card,.profile-panel,.profile-next{position:relative;overflow:hidden}.profile-hero-card{margin-top:34px;padding:34px;display:grid;grid-template-columns:auto 1fr auto;gap:26px;align-items:center;border:1px solid rgba(255,255,255,.075);border-radius:28px;background:radial-gradient(circle at 75% 20%,rgba(37,55,82,.4),transparent 42%),linear-gradient(145deg,#0d1726,#09111d);box-shadow:0 28px 90px rgba(0,0,0,.28)}
      .profile-hero-card:before,.profile-panel:before,.profile-next:before{content:"";position:absolute;inset:-2px;border-radius:inherit;padding:1px;background:conic-gradient(from 0deg,transparent 0 55%,rgba(217,180,91,.9) 66%,rgba(92,203,255,.75) 72%,transparent 82%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;animation:profile-neon-spin 7s linear infinite;pointer-events:none;opacity:.8}.profile-panel:before{animation-duration:9s;opacity:.5}.profile-next:before{animation-duration:8s;opacity:.65}@keyframes profile-neon-spin{to{transform:rotate(360deg)}}
      .profile-avatar{width:126px;height:126px;border-radius:32px;display:grid;place-items:center;background:linear-gradient(145deg,#1a2a42,#0d1725);border:1px solid rgba(217,180,91,.2);color:#d9b45b;font-size:58px;position:relative;overflow:visible;box-shadow:0 0 0 1px rgba(92,203,255,.08),0 0 18px rgba(217,180,91,.12),inset 0 1px rgba(255,255,255,.05);animation:avatar-glow 3.2s ease-in-out infinite}@keyframes avatar-glow{0%,100%{box-shadow:0 0 0 1px rgba(92,203,255,.08),0 0 14px rgba(217,180,91,.1),inset 0 1px rgba(255,255,255,.05)}50%{box-shadow:0 0 0 1px rgba(92,203,255,.2),0 0 28px rgba(217,180,91,.25),0 0 46px rgba(92,203,255,.08),inset 0 1px rgba(255,255,255,.05)}}.profile-avatar img{width:100%;height:100%;object-fit:cover;border-radius:31px}.profile-online{position:absolute;bottom:-9px;right:12px;background:#0b1320;border-radius:20px;padding:5px 9px;font-size:10px;font-weight:900;white-space:nowrap;z-index:2}.profile-online.online{border:1px solid rgba(143,208,159,.35);color:#8fd09f}.profile-online.offline{border:1px solid rgba(154,166,184,.25);color:#9aa6b7}
      .profile-main-info h1{font-family:Estedad,Vazirmatn,sans-serif;font-size:clamp(32px,5vw,52px);margin:3px 0 8px;letter-spacing:-.04em}.profile-location{color:#aeb6c5;margin:0;font-size:14px}.profile-tags{display:flex;gap:8px;margin-top:17px;flex-wrap:wrap}.profile-tags span{font-size:10px;color:#9aa5b6;border:1px solid rgba(255,255,255,.08);background:#0a111d;padding:7px 10px;border-radius:999px}.profile-actions{display:flex;flex-direction:column;gap:9px;min-width:175px}.profile-actions .primary-btn{width:100%}.secondary-btn{border:1px solid rgba(217,180,91,.28);color:#d9b45b;padding:12px 18px;border-radius:13px;text-align:center;font-weight:800;background:rgba(217,180,91,.04)}
      .profile-content-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:16px;margin-top:18px}.profile-panel{min-height:245px;padding:28px;border:1px solid rgba(255,255,255,.065);border-radius:24px;background:linear-gradient(145deg,#0c1421,#09111c);position:relative}.profile-panel h2{font-family:Estedad,Vazirmatn,sans-serif;font-size:23px;margin:0 0 17px}.profile-panel>p{color:#aeb6c5;line-height:2.1;margin:0;max-width:680px}.panel-kicker{color:#d9b45b;font-size:11px;font-weight:900;margin-bottom:12px;opacity:.8}.muted{color:#7f8b9e!important}.profile-skills{display:grid;gap:9px}.profile-skill{display:flex;align-items:center;gap:12px;padding:11px 12px;border-radius:15px;background:#0a111d;border:1px solid rgba(255,255,255,.05)}.skill-icon{width:37px;height:37px;display:grid;place-items:center;border-radius:11px;background:#16243a;color:#d9b45b;font-size:20px;box-shadow:0 0 16px rgba(217,180,91,.1)}.profile-skill strong,.profile-skill small{display:block}.profile-skill strong{font-size:13px}.profile-skill small{font-size:10px;color:#7f8b9e;margin-top:3px}.profile-next{margin-top:18px;padding:30px 32px;display:flex;align-items:center;justify-content:space-between;gap:20px;border:1px solid rgba(217,180,91,.2);border-radius:24px;background:linear-gradient(100deg,#17140d,#0b1421)}.profile-next h2{font-family:Estedad,Vazirmatn,sans-serif;margin:3px 0 7px;font-size:25px}.profile-next>div>p:last-child{margin:0;color:#929daf;font-size:13px;line-height:1.8}.profile-empty{margin-top:40px;padding:70px;text-align:center;border:1px solid rgba(255,255,255,.07);border-radius:24px;color:#9ba6b8}
      @media(max-width:800px){.profile-hero-card{grid-template-columns:auto 1fr;padding:24px;gap:18px}.profile-actions{grid-column:1/-1;display:grid;grid-template-columns:1fr 1fr;min-width:0}.profile-content-grid{grid-template-columns:1fr}.profile-next{display:block}.profile-next .primary-btn{width:100%;margin-top:18px}}@media(max-width:560px){.profile-page{padding-bottom:55px}.profile-nav{height:70px}.back-link{font-size:11px}.profile-hero-card{grid-template-columns:1fr;text-align:center;padding:22px;margin-top:20px}.profile-avatar{margin:auto;width:105px;height:105px;border-radius:28px}.profile-avatar img{border-radius:27px}.profile-main-info h1{font-size:34px}.profile-tags{justify-content:center}.profile-actions{grid-template-columns:1fr}.profile-content-grid{margin-top:12px}.profile-panel{padding:22px;min-height:0}.profile-next{padding:24px 21px}.profile-next h2{font-size:22px}}
    `}</style>
  </main>;
}
